// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxViYrFr4DY3cefjZ9lXgY1mLDXPxq_po',
    appId: '1:64876880789:web:a5e6bdf1830b822768cc9c',
    messagingSenderId: '64876880789',
    projectId: 'what-to-do-f74dc',
    authDomain: 'what-to-do-f74dc.firebaseapp.com',
    storageBucket: 'what-to-do-f74dc.firebasestorage.app',
    measurementId: 'G-T0HXSDLBP3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUlTidpcYlUf3UzCoQ2RoUErU0P1cCanc',
    appId: '1:64876880789:android:033d7e9c50fc6f6468cc9c',
    messagingSenderId: '64876880789',
    projectId: 'what-to-do-f74dc',
    storageBucket: 'what-to-do-f74dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBFbn_dojmCJBnr-NZlVqgTMxlAOp1M84',
    appId: '1:64876880789:ios:ecb747d5feaea11568cc9c',
    messagingSenderId: '64876880789',
    projectId: 'what-to-do-f74dc',
    storageBucket: 'what-to-do-f74dc.firebasestorage.app',
    iosBundleId: 'com.example.fpWhatTodo',
  );
}
